export enum OrderStatus {
    EN_ATTENTE_DOFFRE = 'EN_ATTENTE_DOFFRE',
    PAIEMENT_EN_ATTENTE = 'PAIEMENT_EN_ATTENTE',
    OFFRE_RECUE = 'OFFRE_RECUE',
    OFFRE_ACCEPTEE = 'OFFRE_ACCEPTEE',
    PAIEMENT_RECU = 'PAIEMENT_RECU',
    EN_ATTENTE_DE_RETRAIT = 'EN_ATTENTE_DE_RETRAIT',
    RETIRE = 'RETIRE',
    TRAJET_EN_COURS = 'TRAJET_EN_COURS',
    LIVRE = 'LIVRE',
    TRAJET_VALIDE = 'TRAJET_VALIDE',
    LIVRAISON_VALIDEE = 'LIVRAISON_VALIDEE'
}
