export enum VehicleType {
    AUDI_A1 = 'AUDI_A1',
    AUDI_A3 = 'AUDI_A3',
    AUDI_A5 = 'AUDI_A5',
    AUDI_A6 = 'AUDI_A6',
    BMW = 'BMW',
    CITROEN_C1 = 'CITROEN_C1',
    CITROEN_C2 = 'CITROEN_C2',
    CITROEN_C3 = 'CITROEN_C3',
    CITROEN_C4 = 'CITROEN_C4',
    CITROEN_C5 = 'CITROEN_C5',
    OTHER_FORD = 'OTHER_FORD',
    FORD_FOCUS = 'FORD_FOCUS',
    MERCEDES_CLASS_A = 'MERCEDES_CLASS_A',
    OPEL_ASTRA = 'OPEL_ASTRA',
    PEUGEOT = 'PEUGEOT',
    VOLKSWAGEN = 'VOLKSWAGEN',
    OTHER_VEHICLE = 'OTHER_VEHICLE'
}
