#version: '3.3'
#
#services:
#    osrm:
#        image: osrm/osrm-backend
#        ports:
#            - "9966:9966"

#
#
#version: '3.4'
#
#services:
#    test_web:
#        image: ${DOCKER_REGISTRY-}osrmweb
#        build:
#            context: .
#            dockerfile: OSRM_WEB/Dockerfile
#        ports:
#            - 1111
#
#    osrm-data:
#        image: irony/osrm5
#        volumes:
#            - /data
#
#    osrm:
#        image: irony/osrm5
#        volumes:
#            - osrm-data
#        ports:
#            - 5000:5000
#        command: ./start.sh Sweden http://download.geofabrik.de/europe/belgium-latest.osm.pbf
